---
title: "Plots MT"
author: "Raphael Kroes"
date: "2023-11-22"
output: html_document
---

```{r}
#Heatwaves: 95% quantile

library(ggplot2)
wetter.baiersbronn <- read.csv("C:/Users/Raphael (limited)/Desktop/Master Thesis/weather data/wetter baiersbronn.csv")
row.selector<- 13+seq(0,365*24, by=24)
temperatures<- as.numeric(wetter.baiersbronn$temperature_2m...C.[row.selector])
dates<- as.Date(substr(wetter.baiersbronn$time[row.selector],1,10))
df<- data.frame(date = dates, temperature = temperatures)
threshold <- quantile(df$temperature, 0.95)
plot_1 <- ggplot(df, aes(x = date, y = temperature)) +
  geom_line() +  # Add a line to connect the points
  labs(title = "Temperature Time Series",
       x = "Date",
       y = "Temperature (in degrees)") +
  theme_minimal()  # Customize the theme if needed

plot_2 <- ggplot(df, aes(x = date, y = temperature, fill = temperature > threshold)) +
  geom_bar(stat = "identity") +  # Create a bar plot
  scale_fill_manual(values = c("skyblue", "red"),
                    name = "Temperature regime",
                    labels = c("temperatures below 95% quantile", "temperatures above 95% quantile")) +  # Set fill colors, legend title, and labels
  labs(title = "Daily Ambient Temperature in Baiersbronn, 2016",
       x = "Date",
       y = "Temperature (in degrees)") +
  theme_minimal() +  # Customize the theme if needed
  theme(legend.position = "bottom")
print(plot_1)
print(plot_2)
```
```{r}
#######descriptive plots#######

library(ggplot2)
############## TO DO ##############
# Weather Plots
# Daylight Plots
# Age distribution
# (unbalanced?) distribution of disease category
# SDI param plots: daily effect (3d) & accumulated effects

#prepare data

n<- length(levels(full.df_7$week))
sel.quantiles_age<- c(0.05,0.25,0.5,0.75,0.95)
age.matrix<- matrix(NA, nrow = n, ncol = length(sel.quantiles_age))
colnames(age.matrix)<- paste0("age_q_",sel.quantiles_age)
gender.vec<- numeric(n)
phi.vec<- numeric(n)
sel.quantiles_chronic<- c(0.05,0.25,0.5,0.75,0.95)
chronic.matrix<- matrix(NA, nrow = n, ncol = length(sel.quantiles_chronic))
colnames(chronic.matrix)<- paste0("chronic_q_",sel.quantiles_chronic)
mean.temperature<- numeric(n)

for(i in seq(1,n)){
  im<- full.df_7|>
    filter(week==levels(full.df_7$week)[i])
  age.matrix[i,]<- quantile(im$age,probs = sel.quantiles_age)
  gender.vec[i]<- mean(im$female)
  phi.vec[i]<- mean(im$PKV)
  chronic.matrix[i,]<- quantile(im$no_all_chronic_diseases, probs = sel.quantiles_chronic)
  mean.temperature[i]<- mean(im$daily_mean_temperature_kelvin)
}

df<- as.data.frame(cbind(as.numeric(levels(full.df_7$week)),
                         age.matrix,
                         gender.vec,
                         phi.vec,
                         chronic.matrix,
                         mean.temperature-273.16))
colnames(df)[1]<- "week"
colnames(df)[14]<- "mean.temperature"

# Define the colours for the quantiles
colours <- c("#FFD6D6", "#FFADAD", "#FF8585", "#FF5C5C", "#FF3333")

# Create the plot
ggplot(df, aes(x = week)) +
  geom_ribbon(aes(ymin = age_q_0.05, ymax = age_q_0.25, fill = "0.05-0.25"), alpha = 0.8, colour = NA) +
  geom_ribbon(aes(ymin = age_q_0.25, ymax = age_q_0.5, fill = "0.25-0.5"), alpha = 0.8, colour = NA) +
  geom_ribbon(aes(ymin = age_q_0.5, ymax = age_q_0.75, fill = "0.5-0.75"), alpha = 0.8, colour = NA) +
  geom_ribbon(aes(ymin = age_q_0.75, ymax = age_q_0.95, fill = "0.75-0.95"), alpha = 0.8, colour = NA) +
  scale_fill_manual(values = colours, guide = FALSE) +
  theme_minimal() +
  labs(x = "Week", y = "Value") +
  ggtitle("Age Quantiles by Week") +
  theme(plot.title = element_text(hjust = 0.5))

library(ggplot2)

# Define the colours for the quantiles
colours <- c("#FFD6D6", "#FFADAD", "#FF8585", "#FF5C5C", "#FF3333")

# Create the plot
ggplot(df, aes(x = week)) +
  # geom_ribbon(aes(ymin = age_q_0.05, ymax = age_q_0.25, fill = "0.05-0.25"), alpha = 0.8, colour = NA) +
  # geom_ribbon(aes(ymin = age_q_0.25, ymax = age_q_0.5, fill = "0.25-0.5"), alpha = 0.8, colour = NA) +
  # geom_ribbon(aes(ymin = age_q_0.5, ymax = age_q_0.75, fill = "0.5-0.75"), alpha = 0.8, colour = NA) +
  # geom_ribbon(aes(ymin = age_q_0.75, ymax = age_q_0.95, fill = "0.75-0.95"), alpha = 0.8, colour = NA) +
  geom_line(aes(y = age_q_0.05), colour = "blue", linewidth = 1.1) +
  geom_line(aes(y = age_q_0.25), colour = "green", linewidth = 1.1) +
  geom_line(aes(y = age_q_0.5), colour = "black", linewidth = 1.1) +
  geom_line(aes(y = age_q_0.75), colour = "green", linewidth = 1.1) +
  geom_line(aes(y = age_q_0.95), colour = "blue", linewidth = 1.1) +
  scale_fill_manual(values = colours, guide = FALSE) +
  scale_x_continuous(name = "week", breaks = c(1,seq(4,53,by=4))) +
  theme_minimal() +
  labs(x = "Week", y = "Age") +
  ggtitle("Age Quantiles by Week") +
  theme(plot.title = element_text(hjust = 0.5)) 

ggplot(df, aes(x = week)) +
  geom_line(aes(y = mean.temperature), colour = "black") +  
  scale_x_continuous(name = "week", breaks = c(1,seq(4,53,by=4))) +
  scale_fill_manual(values = colours, guide = FALSE) +
  theme_minimal() +
  labs(x = "Week", y = "Temperature in °C") +
  ggtitle("Temperature by Week") +
  theme(plot.title = element_text(hjust = 0.5)) 

```
```{r}
### Harvesting simulation

n_mc<- 81
patients<- 1000
p_disease<- function(k) ifelse(k > 11 & k <= 21, 0.055, 0.05)
p_recovery<- 0.2
healthy<- numeric(n_mc)
diseased<- numeric(n_mc)
healthy[1]<- 800
diseased[1]<- 200
healthy_nr<- numeric(n_mc)
diseased_nr<- numeric(n_mc)
healthy_nr[1]<- 800
diseased_nr[1]<- 200
set.seed(6565)
for(i in seq(2, n_mc)){
  recovered_nr<- diseased_nr[i - 1] * p_recovery
  fallen_nr<- healthy_nr[i - 1] * p_disease(i)
  healthy_nr[i]<- healthy_nr[i - 1] - fallen_nr + recovered_nr
  diseased_nr[i]<- patients - healthy_nr[i]
  
  recovered<- sum(sample(c(1, 0), diseased[i - 1], replace = TRUE,
                         prob = c(p_recovery, 1 - p_recovery)))
  fallen<- sum(sample(c(1, 0), healthy[i - 1], replace = TRUE,
                         prob = c(p_disease(i), 1 - p_disease(i))))
  healthy[i]<- healthy[i - 1] - fallen + recovered
  diseased[i]<- patients - healthy[i]
}
im<- data.frame(healthy = healthy, healthy_nr = healthy_nr, time = seq(0, 80))
library(ggplot2)
harvest.plot<- ggplot(data = im, aes(x = time, y = healthy)) +
  geom_rect(aes(xmin = 10, xmax = 20, ymin = -Inf, ymax = Inf), fill = "grey", 
            alpha = 0.05) +
  geom_line(aes(x = time, y = healthy, colour = "random simulation")) +
  geom_line(aes(y = healthy_nr, colour = "no randomness")) +
  labs(title = "Stylised Simulation of Harvesting", x = "time", 
       y = "number of healthy patients") +
  scale_color_manual(values = c("red", "blue"), 
                     labels = c("no randomness", "random simulation")) +
  theme(legend.position = "bottom")
harvest.plot
ggsave("harvest_sim.png", plot = harvest.plot, width = 8, height = 4.5, device = "png")

```
```{r}
#TDI visualisation
tdi<- function(T, RH){
  0.45 * T - 0.08 * RH + 5.5 / 1000 * T * RH + 8
}
t.vec<- seq(-10, 35)
rh.vec<- seq(0, 1, by = 0.1)
tdi.vec<- list()
for(i in seq_along(rh.vec)){
  tdi.vec[[i]]<- unlist(sapply(t.vec, function(x) tdi(x, rh.vec[i])))
}
tdi.vec<- unlist(tdi.vec)
tdi.vis.df<- data.frame(TDI = tdi.vec, RH = order(rep(rh.vec, length(t.vec))),
                        T = rep(t.vec, length(rh.vec)))|>
  arrange(T, RH)

persp(x = tdi.vis.df$T, y = tdi.vis.df$RH, z = tdi.vis.df$TDI)
```

```{r}
# hyperparameter visualisation
hyper.vis<- function(hyp.element){
  params<- hyp.element$best_in_class
  sdi.params<- c(params$no.lags, params$sdi.alpha, params$sdi.beta,
                 params$theta_1, params$theta_2, params$theta_3, params$rho_1,
                 params$rho_2, params$rho_3, params$tau)
  
}

library(ggplot2)
sdi.vis_w<- function(hyp.vec, hyp.name){
  #weights
  lag<- seq(1, hyp.vec[1])
  omega<- dbetabinom.ab(x = lag, size = hyp.vec[1], shape1 = 
                          hyp.vec[2], shape2 = hyp.vec[3])
  wdf<- data.frame(lag = 0:21, omega = c(omega, rep(0, 22 - hyp.vec[1])))
  wp<- ggplot(data = wdf, aes(x = lag, y = omega)) +
    geom_line() +
    labs(title = paste0("Discomfort index weight lags (", hyp.name, ")"),
         x = "lag no.", y = "weight")
  ggsave(filename = paste0("weights_", hyp.name, ".png"), device = "png",
         width = 16, height = 12, units = "cm")
}
sdi.vis_dd<- function(hyp.vec, hyp.name){
  #daily discomfort
  T_Celsius<- seq(-7, 30)
  T_Kelvin<- T_Celsius + 273.16
  humidity<- seq(0, 1, by = 0.2)
  DI.mat<- matrix(NA, nrow = length(T_Celsius), ncol = length(humidity))
  for(i in seq_along(T_Celsius)){
    for(j in seq_along(humidity)){
      t<- T_Kelvin[i]
      h<- humidity[j]
      pars<- c(t, t^2, t^3, h, h^2, h^3, t * h)
      DI.mat[i, j]<- hyp.vec[4:10] %*% pars
    }
  }
  DI.data<- data.frame(T_C = rep(T_Celsius, length(humidity)),
                       DI = as.vector(DI.mat),
                       humidity = sort(rep(humidity, length(T_Celsius))))
  DI.data$DI<- scale(DI.data$DI)
  plot(DI~T_C, data = DI.data)
  DIp<- ggplot(data = DI.data, aes(x = T_C, y= DI, col = humidity)) +
    scale_colour_gradient(low = "blue", high = "red") +
    geom_point(aes(x = T_C, y= DI, col = humidity)) +
    
    labs(title = paste0("day-specific discomfort level (", hyp.name, ")"), 
         x = "temperature (°C)", y = "single day discomfort (standardised)", 
         colour = "humidity")
  ggsave(filename = paste0("dailydisc_", hyp.name, ".png"), device = "png",
         width = 16, height = 12, units = "cm")
}

sdi.hyp_q1<- c(7, 0.629, 3.213, 0.291, 0.020, 0.142, -0.035, 0.055, 0.039, 
               -0.207)
sdi.hyp_q2<- c(8, 1.900, 3.545, 0.683, -0.055, 0.109, 0.297, 0.227, -0.150, 
               0.026)
sdi.vis_w(sdi.hyp_q1, "research question 1")
sdi.vis_dd(sdi.hyp_q1, "research question 1")
sdi.vis_w(sdi.hyp_q2, "research question 2")
sdi.vis_dd(sdi.hyp_q2, "research question 2")


```
```{r}
# redrawn Q2 month plots
#clear work space and read in datasets
short.names<- c("digestive", "respiratory", "endocrine", "genitourinary", 
                "cardiovascular", "mental", "musculoskeletal", "others")
long.names<- c("diseases of the digestive system",
               "diseases of the respiratory system",
               "endocrine, nutritional, and metabolic disorders",
               "genitourinary disorders",
               "major cardivascular diseases", 
               "mental and behavioural disorders",
               "musculoskeletal disorders",
               "other diseases and injuries")
for(i in seq(1, 8)){
  df<- get(ls()[i + 4])
  plot.name<- paste("Effects of month on", long.names[i])
  file.name<- paste0("Q2 month_", short.names[i], "_redone.png")
  plot_i<- ggplot(data = df, 
                  aes(x = input, y = outcome, col = as.factor(quant))) +
    coord_cartesian(ylim = c(0, 1)) +
    geom_line() +
    scale_x_continuous(breaks = 1:12,
                       labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
    labs(title = plot.name, x = "month", y = "proportion") +
    scale_colour_manual(values = c("0.05" = "red", "0.25" = "blue", 
                                   "0.5" = "black", "0.75" = "blue",
                                   "0.95" = "red")) +
    labs(colour = "quantile") +
    theme(legend.position = "bottom")
    ggsave(filename = file.name, device = "png")
}
```


